reservester/config/routes.rb
Reservester::Application.routes.draw do
  get "restaurants/edit"
  root to: "restaurants#index"
  resources :restaurants

  

  

end

reservester/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, :description, :full_address, :phone_number, presence: true, 
	                    										 length: { minimum: 5 }
	#belongs_to :owner
	mount_uploader :image, ImageUploader
end

reservester/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

reservester/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
  end
  
  def new
  	@restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant].permit(:name, :description, :full_address, :phone_number, :image ))
 
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end
 
  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def index
  	@restaurants = Restaurant.all
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(params[:restaurant].permit(:name, :description, :full_address, :phone_number, :image ))
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :full_address, :phone_number, :image)
  end
end

reservester/app/helpers/application_helper.rb
module ApplicationHelper
end

reservester/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

reservester/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

reservester/app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => {:multipart => true} do |t| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= t.label :name %><br>
    <%= t.text_field :name %>
  </p>
 
  <p>
    <%= t.label :description %><br>
    <%= t.text_area :description %>
  </p>
 
  <p>
    <%= t.label :full_address %><br>
    <%= t.text_area :full_address %>
  </p>

  <p>
    <%= t.label :phone_number %><br>
    <%= t.text_field :phone_number %>
  </p>

  <p>
    <%= t.label :image %>
    <%= image_tag(@restaurant.image_url) if @restaurant.image? %>
    <%= t.file_field :image %>
    <%= t.hidden_field :image_cache %>
  </p>

  <p>
    <%= t.submit %>
  </p>
 <% end %>

reservester/app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>
<%= form_for :restaurant, url: restaurant_path(@restaurant), method: :patch do |t| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
  	<h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
  	  this restaurant from being saved:</h2>
  	<ul>
  	<% @restaurant.errors.full_messages.each do |msg| %>
  	  <li><%= msg %></li>
  	<% end %>
    </ul>
  </div>
  <% end %>
  <%= render 'form' %>
 <% end %>

 <%= link_to 'Back', restaurants_path %>
 

reservester/app/views/restaurants/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Home", root_path %>
<%= link_to 'New restaurant', new_restaurant_path %>
<table>
  <tr>
    <th>Restaurant Name</th>
    <th>Restaurant Description</th>
    <th>Restaurant Full Address</th>
    <th>Restaurant Phone Number</th>
  </tr>
 
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.full_address %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= restaurant.image %></td>
      <td><%= link_to 'Show', restaurant %></td>
      <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      <td><%= link_to 'Destroy', restaurant_path(restaurant),
                      method: :delete, data: { confirm: 'Are you sure?'                
  } %></td>

      <td><%=image_tag restaurant.image.thumb if restaurant.image.present? %></td>   

    </tr>
  <% end %>
  </table>

reservester/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= form_for :restaurant, url: restaurants_path do |t| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= render 'form' %>
 <% end %>

 <%= link_to 'Back', restaurants_path %>

 

reservester/app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>
  <strong>Restaurant Name:</strong>
  <%= @restaurant.name%>
</p>
 
<p>
  <strong>Restaurant Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Restaurant Full Address:</strong>
  <%= @restaurant.full_address %>
</p>

<p>
  <strong>Restaurant Phone Number:</strong>
  <%= @restaurant.phone_number %>
</p>


<%= image_tag @restaurant.image.masthead if @restaurant.image.present? %>


<p>
  <%= link_to "Add an Image", image_path(:restaurant_id => @restaurant) %> |
  <%= link_to 'Back', restaurants_path %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
</p>